/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as GameLogImport } from './routes/game-log'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const GameLogRoute = GameLogImport.update({
  id: '/game-log',
  path: '/game-log',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/game-log': {
      id: '/game-log'
      path: '/game-log'
      fullPath: '/game-log'
      preLoaderRoute: typeof GameLogImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-log': typeof GameLogRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-log': typeof GameLogRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/game-log': typeof GameLogRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game-log'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game-log'
  id: '__root__' | '/' | '/game-log'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GameLogRoute: typeof GameLogRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GameLogRoute: GameLogRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/game-log"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/game-log": {
      "filePath": "game-log.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
